### ISSUE TITLE
idoc init 报错

### ISSUE THREAD

**Issue by fancyboynet** [jaywcjlove/idoc#15]
```
/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:549
    throw e;
          ^
ReferenceError: answers is not defined
    at menu_json (/usr/local/lib/node_modules/idoc/lib/menu_json.js:26:44)
    at null.completed (/usr/local/lib/node_modules/idoc/lib/init.js:136:31)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/idoc/node_modules/inquirer/lib/ui/prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/idoc/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)

```

**Comment by jaywcjlove** [comment]
@fancyboynet 这个问题解决了还没有打版本，没有publish，你需要文件夹内建立一个 `*.md`文件

**Comment by fancyboynet** [comment]
@jaywcjlove 嗯，可以了，顺便问下 idoc build 是否支持指定输出目录？类似
```
idoc build output
```
类似源码跟发布分开

**Comment by jaywcjlove** [comment]
@fancyboynet  输出什么样的目录？ HTML吗？

**Comment by fancyboynet** [comment]
@jaywcjlove 对，就是把编译出的html全部放在output目录下，这样版本只需要控制“源码”，忽略output

**Comment by fancyboynet** [comment]
虽然现在也可以做到，不过感觉有一个指定输出目录会更好一些

**Comment by jaywcjlove** [comment]
这个很简单的，我就把生成的目录拷贝到另外一个地方，回头有空搞出来。
放倒跟目录的原因是，Github 的 gh-pages 根目录需要`index.html`就能直接预览

**Comment by fancyboynet** [comment]
@jaywcjlove 嗯，谢啦

**Comment by fancyboynet** [comment]
@jaywcjlove 发现个新问题
```
idoc watch
```
无法退出，ctrl + c并没有真的退出，修改.md后还是会自动更新

**Comment by jaywcjlove** [comment]
@fancyboynet 我的没有这个问题哦，进程没有退出来？你是什么平台  window  还是Mac 是什么系统版本呢？我测试测试。

**Comment by fancyboynet** [comment]
@jaywcjlove mac 10.11

**Comment by fancyboynet** [comment]
@jaywcjlove 不好意思，好像又可以了，可能跟我的IDE有关系，直接用file://是正常的

**Comment by jaywcjlove** [comment]
@fancyboynet 新版本修复了已经`publish`了，更新`idoc@0.2.8`
