### ISSUE TITLE
执行idoc命令时报错

### ISSUE THREAD

**Issue by zhufengnodejs** [jaywcjlove/idoc#21]
```bash
D:\vip_data\idoc>idoc
C:\Users\Administrator\AppData\Roaming\npm\node_modules\idoc\node_modules\colorful\index.js:22
    Object.defineProperty(String.prototype, key, {
           ^

TypeError: Cannot redefine property: black
    at Function.defineProperty (native)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\idoc\node_modules\colorful\index.js:22:12
    at Array.forEach (native)
    at Object.exports.toxic (C:\Users\Administrator\AppData\Roaming\npm\node_modules\idoc\node_modules\colorful\index.js:20:23)

    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\idoc\.bin\idoc.js:7:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by zhufengnodejs** [comment]
我看了一下代码,应该是String.prototype上面已经有了black的属性，
在idoc\node_modules\colorful\index.html加一句话就可以
```diff
  Object.keys(colors).forEach(function(key) {
    var fn = colors[key];
+    if(!String.prototype[key])
    Object.defineProperty(String.prototype, key, {
      get: function() {
        return fn(this.valueOf());
      }
    });
  });
```

**Comment by jaywcjlove** [comment]
cb253ba7150a23460c9f557d47d4a8aca1ba006a

我将命令行显示颜色的工具`colorful` 更改成我自己写的 [colors-cli](https://github.com/jaywcjlove/colors-cli)，`colorful` 工具估计更新了，package.json 更改小版本变更，更稳定。

**Comment by zhufengnodejs** [comment]
谢谢
