### ISSUE TITLE
window 8.1 idoc build 报错

### ISSUE THREAD

**Issue by wing324** [jaywcjlove/idoc#8]
window 8.1 上面报错idoc v0.2.4

```
fs.js:799
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'E:\Wing's Github\idoc\html\E:\W
ing's Github\idoc'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at mkdirsSync (C:\Users\wing324\AppData\Roaming\npm\node_modules\idoc\lib\fi
le.js:53:31)
    at Object.write (C:\Users\wing324\AppData\Roaming\npm\node_modules\idoc\lib\
file.js:105:5)
    at C:\Users\wing324\AppData\Roaming\npm\node_modules\idoc\lib\build.js:91:14

    at Array.forEach (native)
    at build (C:\Users\wing324\AppData\Roaming\npm\node_modules\idoc\lib\build.j
s:48:13)
    at module.exports (C:\Users\wing324\AppData\Roaming\npm\node_modules\idoc\in
dex.js:33:16)
    at Object.<anonymous> (C:\Users\wing324\AppData\Roaming\npm\node_modules\ido
c\.bin\idoc.js:67:1)
    at Module._compile (module.js:434:26)
```

**Comment by jaywcjlove** [comment]
#9 bug 修复 更新 v0.2.5
